### ----------------------------------------------------------------LOGIN---------------


###   LOGIN
POST http://127.0.0.1:8080/account/login
Content-Type: application/json

{
  "nombre": "fran",
  "password": "olivia1506"
}

### -----------------------------------------------------------------USER---------------

### Obtener todos los usuarios con autenticación
GET http://127.0.0.1:8080/account/getAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21icmUiOiJmcmFuIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NTA4OTIzMTgsImV4cCI6MTc1MDg5MjQ5OH0.TJFu4fxLmXwshxa5W-U3hSlZfdb7AnExMoXXLevelVs

### -----------------------------------------------------------------------------------

### busca por ID de mongo
GET http://127.0.0.1:8080/account/usuario/6854939b3901b331d78cd38c

### -----------------------------------------------------------------------------------

### crea un elemento en mongo + JSON (service + repo + model + DB)
POST http://127.0.0.1:8080/account/crearUsuario
Content-Type: application/json

{
    "nombre": "Rubinstein",
    "email": "stenwey@mail.com",
    "password": 123344
}

### -----------------------------------------------------------------------------------

### modificar una cuenta por id
PUT http://127.0.0.1:8080/account/modificarMail/6852469e308dcdd437634302
Content-Type: application/json

{
    "email": "fegocosa@mail.com"
}

### -----------------------------------------------------------------------------------                            

### elimina una cuenta por id
DELETE http://127.0.0.1:8080/account/borrarCuenta/685c7fa739320512a92dd430






### -------------------FOTOS------------------------------------------------------------  

### obtener todas las fotos
GET http://127.0.0.1:8080/fotos/all

### -----------------------------------------------------------------------------------   

### 
GET http://127.0.0.1:8080/fotos/foto/6853653346a6dd051ba1e79d

### -----------------------------------------------------------------------------------   

###
DELETE http://127.0.0.1:8080/fotos/borrarFoto/68526c4fb58e525c0bd2d992



### -----------------------------------------------------------------------------------   

