### busca todos los usuarios
GET http://127.0.0.1:8080/account/getAll

### busca por ID de mongo
GET http://127.0.0.1:8080/account/usuario/68523d87526f042b15c2b104

### crea un elemento en mongo + JSON (service + repo + model + DB)
POST http://127.0.0.1:8080/account/crearUsuario
Content-Type: application/json

{
    "nombre": "terminator",
    "email": "eeee@mail.com",
    "password": 1145
}

### modificar una cuenta por id
PUT http://127.0.0.1:8080/account/modificarMail/6852469e308dcdd437634302
Content-Type: application/json

{
    "email": "fegocosa@mail.com"
}

### elimina una cuenta por id
DELETE http://127.0.0.1:8080/account/borrarCuenta/68524841ddf09a9d81ee1ad4





### obtener todas las fotos
GET http://127.0.0.1:8080/fotos/all

### 
GET http://127.0.0.1:8080/fotos/foto/685251618f7d0228d9c3b719

###
POST http://127.0.0.1:8080/fotos/agregarFoto
Content-Type: application/json

{
    "titulo": "francisco",
    "descripcion": "fran@mail.com"
}

### 
PUT http://127.0.0.1:8080/fotos/modificarFoto/685251618f7d0228d9c3b719
Content-Type: application/json

{
    "descripcion": "nueva descripcion"
}

###
DELETE http://127.0.0.1:8080/fotos/borrarFoto/685251618f7d0228d9c3b719